server:
  port: ${port:8201}

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
  client:
    serviceUrl:
      defaultZone: http://${DISCOVERY_HOSTNAME:localhost}:8761/eureka/

management:
  security:
    enabled: false
    
logging:
  level:
    org.chiwooplatform.cloud.sample.rest: DEBUG 
    org.chiwooplatform.cloud.sample: DEBUG

